:stopwatch: Tests are more forgiving on slow, virtual devices
Virtual Android devices cause test failures. Tests have been made more
generous with timing (e.g. rotation can take as long as three seconds on
virtualized hardware).

fixes:
```
java.lang.AssertionError: Started, time elapsed should return should be less than 60 ms
Expected: a value less than <60L>
but: <67L> was greater than <60L>
...
but: <126L> was greater than <110L>
...
but: <205L> was greater than <160L>
...
but: <88L> was greater than <60L>
...
but: <96L> was greater than <60L>
```